server:
  port: 9090

spring:
  jpa:
    #是否在控制台打印sql语句
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        # 隐私转换策略，如果实体类上没有@TableName注解，则默认适用于该策略
        implicit-strategy: com.test.security.rbac.repository.support.AppImplicitNamingStrategy
    #是否自动生成/修改数据库表
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true:

  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    #连接池及重试配置，防止mysql如果8小时自动断开连接问题
    tomcat:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis:  1800000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1

  session:
    #集群session存储方式
    store-type: none
    #session超时时间，单位秒
    timeout: 3000


logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG

#浏览器环境配置项，参见BrowserProperties
app:
  security:
    #浏览器环境配置项，参见BrowserProperties
    browser:
      signInPage: /signIn.html
      singInSuccessUrl: /index.html
      signUpUrl: /signUp.html
      signOutUrl: /logout.html
      responseType: REDIRECT
      rememberMeSeconds: 294000
      #session管理相关配置，参见SessionProperties
      session:
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /session-invalid.html

    # 验证码配置 参见VerificationProperties
    verification:
      #图片验证码配置项，参见ImageCodeProperties
      captcha:
        length: 4
        width: 100
        height: 30
        expireIn: 30
        # 配置需要图形验证码验证的url, 两个验证码如果配的url中相同部分则短信优先级要高
        url: /code/sms

      #短信验证码配置项，参见SmsCodeProperties
      sms:
        length: 6
        expireIn: 60
        # 配置需要短信验证码验证的url
        url:

    #社交登录功能拦截的url,参见SocialProperties
    social:
      # 拦截器处理的url
      filterProcessesUrl: /login/connect
#      signUpUrl:
      #QQ登录配置，参见QQProperties
      qq:
        appId:
        appSecret:
        providerId: qq

      #微信登录配置，参见WeixinProperties
      weixin:
        appId: wxd99431bbff8305a0
        appSecret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin

    #认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
    oauth2:
      # 第三方客户端配置
      clients:
        - clientId: app
          clientSecret: appsecret
          accessTokenValidateSeconds: 3600
          refreshTokenValidateSeconds: 2592000
        - clientId: test
          clientSecret: test
      #OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
      tokenStore: jwt
      #使用jwt时为token签名的秘钥
      jwtSigningKey: aXo3t%12_Ao

