# 基本配置
server:
  port: ${serve.prot:8888}
  servlet:
    context-path: /
    session:
      timeout: 60m

# debug模式
debug: false

# spring配置
spring:
  profiles:
    active: dev

  cache:
#    type: caffeine
#    caffeine:
#      spec: initialCapacity=10,maximumSize=500,expireAfterAccess=3600s
    type: redis
    redis:
      # 全局spring cache缓存失效时间2小时
      time-to-live: 3600000

  redis:
    port: 6379
    timeout: 5000

  output:
    ansi:
      enabled: detect

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  freemarker:
    template-loader-path: classpath:/template/
  mvc:
    static-path-pattern: /statics/**
  resources:
    static-locations: classpath:/statics/
