# 基本配置
server:
  port: ${serve.prot:8888}
  servlet:
    context-path: /
    session:
      timeout: 60m

# debug模式
debug: false

# spring配置
spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=500,expireAfterAccess=86400s

  redis:
    port: 6379
    timeout: 5000

  output:
    ansi:
      enabled: detect

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  freemarker:
    template-loader-path: classpath:/template/
  mvc:
    static-path-pattern: /statics/**
  resources:
    static-locations: classpath:/statics/


#MyBatisPlus配置
mybatis-plus:
  # java目录: classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # resource目录: classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 别名包扫描路径
  typeAliasesPackage: com.starter.app.domain
  # MyBatis-Plus 全局策略配置
  global-config:
    # DB策略配置
    db-config:
      # 全局默认主键类型 :
      # INPUT 用户输入ID
      # ID_WORKER 全局唯一ID，Long类型的主键
      # ID_WORKER_STR 字符串全局唯一IDs
      # UUID 全局唯一ID，UUID类型的主键
      # NONE 该类型为未设置主键类型
      id-type: AUTO
      # 字段策略
      field-strategy: not_null
      # 表名是否使用下划线命名
      table-underline: true
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0

  #原生MyBatis配置
  configuration:
    # 是否开启下划线转驼峰命名规则
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    # cache-enabled: false
    # 配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

---
# 开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 127.0.0.1
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.165:9300
      cluster-name: docker-cluster

mybatis-plus:
  configuration:
    cache-enabled: false

logging:
  level:
    root: info
    com:
      test: debug
#    org:
#      springframework:
#        security: debug
---

# 生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${mysql.host:}:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${mysql.username:}
    password: ${mysql.password:}

  redis:
    host: ${redis.host:}
    password: ${redis.password:}

mybatis-plus:
  configuration:
    cache-enabled: true

logging:
  level:
    root: info
  path: ./logs/

---
