server:
  port: 8885

target-host: localhost

spring:
  redis:
    host: ${target-host}
    redisson:
      file: classpath:redisson.yml

  rabbit:
    host: ${target-host}
    port: 5672
    username: user
    password: bitnami
    virtualHost: /binlog
    apiUrl: http://${target-host}:15672/api/

calf-oplog:
  root: 204
  etcd:
    endpoints: http://${target-host}:2379
  zookeeper:
    url: http://${target-host}:2379


#自动注册客户端(服务端的地址)
databaseEventServerUrl: http://localhost:8885/client/addAll
appName: server-etcd-rabbit-example

