spring:
  redis:
    cluster:
      nodes: 10.11.12.48:8000,10.11.12.48:8001,10.11.12.48:8002,10.11.12.49:8000,10.11.12.49:8001,10.11.12.49:8002
    password: eEn8cEhRD*FU
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      type: batch
      ack-mode: manual
    consumer:
      group-id: kafka-practice
      auto-offset-reset: latest
      enable-auto-commit: false
      # 默认500ms
      fetch-max-wait: 1000
      # 默认500
      max-poll-records: 100
