server:
  port: 9999

spring:
  elasticsearch:
    rest:
      uris: 192.168.2.201:9200
      username: elastic
      password: changeme

# redis地址
spring.redisson.address=redis://192.168.1.204:6379


# 读取列名，进行映射

# rabbitmq连接相关信息(如果只有redis客户端可以不需要使用)

#自动注册客户端(2.1中服务端的地址)
databaseEventServerUrl: http://localhost:8885/client/addAll
#本应用命名
appName: lbt-service-ext-rabbit
# redis地址(rabbitmq实现也要使用redis作为分布式锁)
spring.redisson.address: redis://192.168.1.204:6379
# RabbitMQ配置
spring.rabbit.host: 192.168.1.204
spring.rabbit.port: 5672
spring.rabbit.username: aa
spring.rabbit.password: aa
spring.rabbit.virtualHost: /binlog
spring.rabbit.apiUrl: http://192.168.1.204:15672/api/
